package fysh340.ticket_to_ride.map;


import static fysh340.ticket_to_ride.map.MapCity.*;
import static fysh340.ticket_to_ride.map.MapRouteColor.*;

/**
 * Routes to show on the map
 *
 * @author Shun Sambongi
 * @version 1.0
 * @since 2017-07-22
 */
public enum MapRoute {
    // 7 RED ROUTES
    DENVER_SALT_LAKE_CITY_1(DENVER, SALT_LAKE_CITY, 3, RED, 1),
    DENVER_OKLAHOMA_CITY(DENVER, OKLAHOMA_CITY, 4, RED),
    HELENA_OMAHA(HELENA, OMAHA, 5, RED),
    DALLAS_EL_PASO(DALLAS, EL_PASO, 4, RED),
    CHICAGO_DULUTH(CHICAGO, DULUTH, 3, RED),
    MIAMI_NEW_ORLEANS(MIAMI, NEW_ORLEANS, 6, RED),
    BOSTON_NEW_YORK_1(BOSTON, NEW_YORK, 2, RED, 1),

    // 7 ORANGE ROUTES
    SALT_LAKE_CITY_SAN_FRANCISCO_1(SALT_LAKE_CITY, SAN_FRANCISCO, 5, ORANGE, 1),
    LAS_VEGAS_SALT_LAKE_CITY(LAS_VEGAS, SALT_LAKE_CITY, 3, ORANGE),
    DULUTH_HELENA(DULUTH, HELENA, 6, ORANGE),
    DENVER_KANSAS_CITY_1(DENVER, KANSAS_CITY, 4, ORANGE, 1),
    ATLANTA_NEW_ORLEANS_1(ATLANTA, NEW_ORLEANS, 4, ORANGE, 1),
    CHICAGO_PITTSBURGH_1(CHICAGO, PITTSBURGH, 3, ORANGE, 1),
    NEW_YORK_WASHINGTON_1(NEW_YORK, WASHINGTON, 2, ORANGE, 1),

    // 7 YELLOW ROUTES
    LOS_ANGELES_SAN_FRANCISCO_1(LOS_ANGELES, SAN_FRANCISCO, 3, YELLOW, 1),
    HELENA_SEATTLE(HELENA, SEATTLE, 6, YELLOW),
    DENVER_SALT_LAKE_CITY_2(DENVER, SALT_LAKE_CITY, 3, YELLOW, -1),
    EL_PASO_OKLAHOMA_CITY(EL_PASO, OKLAHOMA_CITY, 5, YELLOW),
    ATLANTA_NEW_ORLEANS_2(ATLANTA, NEW_ORLEANS, 4, YELLOW, -1),
    NASHVILLE_PITTSBURGH(NASHVILLE, PITTSBURGH, 4, YELLOW),
    BOSTON_NEW_YORK_2(BOSTON, NEW_YORK, 2, YELLOW, -1),

    // 7 GREEN ROUTES
    PORTLAND_SAN_FRANCISCO_1(PORTLAND, SAN_FRANCISCO, 5, GREEN, 1),
    DENVER_HELENA(DENVER, HELENA, 4, GREEN),
    EL_PASO_HOUSTON(EL_PASO, HOUSTON, 6, GREEN),
    LITTLE_ROCK_NEW_ORLEANS(LITTLE_ROCK, NEW_ORLEANS, 3, GREEN),
    CHICAGO_SAINT_LOUIS_1(CHICAGO, SAINT_LOUIS, 2, GREEN, 1),
    PITTSBURGH_SAINT_LOUIS(PITTSBURGH, SAINT_LOUIS, 5, GREEN),
    PITTSBURGH_NEW_YORK_1(PITTSBURGH, NEW_YORK, 2, GREEN, 1),

    // 7 BLUE ROUTES
    PORTLAND_SALT_LAKE_CITY(PORTLAND, SALT_LAKE_CITY, 6, BLUE),
    HELENA_WINNIPEG(HELENA, WINNIPEG, 4, BLUE),
    OKLAHOMA_CITY_SANTA_FE(OKLAHOMA_CITY, SANTA_FE, 3, BLUE),
    CHICAGO_OMAHA(CHICAGO, OMAHA, 4, BLUE),
    KANSAS_CITY_SAINT_LOUIS_1(KANSAS_CITY, SAINT_LOUIS, 2, BLUE, 1),
    ATLANTA_MIAMI(ATLANTA, MIAMI, 5, BLUE),
    MONTREAL_NEW_YORK(MONTREAL, NEW_YORK, 3, BLUE),

    // 7 PURPLE ROUTES
    PORTLAND_SAN_FRANCISCO_2(PORTLAND, SAN_FRANCISCO, 5, PURPLE, -1),
    LOS_ANGELES_SAN_FRANCISCO_2(LOS_ANGELES, SAN_FRANCISCO, 3, PURPLE, -1),
    HELENA_SALT_LAKE_CITY(HELENA, SALT_LAKE_CITY, 3, PURPLE),
    DENVER_OMAHA(DENVER, OMAHA, 4, PURPLE),
    KANSAS_CITY_SAINT_LOUIS_2(KANSAS_CITY, SAINT_LOUIS, 2, PURPLE, 1),
    DULUTH_TORONTO(DULUTH, TORONTO, 6, PURPLE),
    CHARLESTON_MIAMI(CHARLESTON, MIAMI, 4, PURPLE),

    // 7 WHITE ROUTES
    SALT_LAKE_CITY_SAN_FRANCISCO_2(SALT_LAKE_CITY, SAN_FRANCISCO, 5, WHITE, -1),
    DENVER_PHOENIX(DENVER, PHOENIX, 5, WHITE),
    CALGARY_WINNIPEG(CALGARY, WINNIPEG, 6, WHITE),
    LITTLE_ROCK_NASHVILLE(LITTLE_ROCK, NASHVILLE, 3, WHITE),
    CHICAGO_SAINT_LOUIS_2(CHICAGO, SAINT_LOUIS, 2, WHITE, -1),
    CHICAGO_TORONTO(CHICAGO, TORONTO, 4, WHITE),
    PITTSBURGH_NEW_YORK_2(PITTSBURGH, NEW_YORK, 2, WHITE, -1),

    // 7 BLACK ROUTES
    EL_PASO_LOS_ANGELES(EL_PASO, LOS_ANGELES, 6, BLACK),
    DENVER_KANSAS_CITY_2(DENVER, KANSAS_CITY, 4, BLACK, -1),
    DULUTH_WINNIPEG(DULUTH, WINNIPEG, 4, BLACK),
    MONTREAL_SAULT_ST_MARIE(MONTREAL, SAULT_ST_MARIE, 5, BLACK),
    CHICAGO_PITTSBURGH_2(CHICAGO, PITTSBURGH, 3, BLACK, -1),
    NASHVILLE_RALEIGH(NASHVILLE, RALEIGH, 3, BLACK),
    NEW_YORK_WASHINGTON_2(NEW_YORK, WASHINGTON, 2, BLACK, -1),


    // 44 GRAY ROUTES

    // 7 NORTH WEST
    CALGARY_VANCOUVER(CALGARY, VANCOUVER, 3, GRAY),
    CALGARY_HELENA(CALGARY, HELENA, 4, GRAY),
    CALGARY_SEATTLE(CALGARY, SEATTLE, 4, GRAY),
    SEATTLE_VANCOUVER_1(SEATTLE, VANCOUVER, 1, GRAY, 1),
    SEATTLE_VANCOUVER_2(SEATTLE, VANCOUVER, 1, GRAY, -1),
    PORTLAND_SEATTLE_1(PORTLAND, SEATTLE, 1, GRAY, 1),
    PORTLAND_SEATTLE_2(PORTLAND, SEATTLE, 1, GRAY, -1),

    // 6 SOUTH WEST
    LAS_VEGAS_LOS_ANGELES(LAS_VEGAS, LOS_ANGELES, 2, GRAY),
    LOS_ANGELES_PHOENIX(LOS_ANGELES, PHOENIX, 3, GRAY),
    PHOENIX_SANTA_FE(PHOENIX, SANTA_FE, 3, GRAY),
    EL_PASO_PHOENIX(EL_PASO, PHOENIX, 3, GRAY),
    EL_PASO_SANTA_FE(EL_PASO, SANTA_FE, 2, GRAY),
    DENVER_SANTA_FE(DENVER, SANTA_FE, 2, GRAY),

    // 10 MISSISSIPPI RIVER
    DULUTH_OMAHA_1(DULUTH, OMAHA, 2, GRAY, 1),
    DULUTH_OMAHA_2(DULUTH, OMAHA, 2, GRAY, -1),
    KANSAS_CITY_OMAHA_1(KANSAS_CITY, OMAHA, 1, GRAY, 1),
    KANSAS_CITY_OMAHA_2(KANSAS_CITY, OMAHA, 1, GRAY, -1),
    KANSAS_CITY_OKLAHOMA_CITY_1(KANSAS_CITY, OKLAHOMA_CITY, 2, GRAY, 1),
    KANSAS_CITY_OKLAHOMA_CITY_2(KANSAS_CITY, OKLAHOMA_CITY, 2, GRAY, -1),
    DALLAS_OKLAHOMA_CITY_1(DALLAS, OKLAHOMA_CITY, 2, GRAY, 1),
    DALLAS_OKLAHOMA_CITY_2(DALLAS, OKLAHOMA_CITY, 2, GRAY, -1),
    DALLAS_HOUSTON_1(DALLAS, HOUSTON, 1, GRAY, 1),
    DALLAS_HOUSTON_2(DALLAS, HOUSTON, 1, GRAY, -1),

    // 7 NORTH OF PITTSBURGH
    SAULT_ST_MARIE_WINNIPEG(SAULT_ST_MARIE, WINNIPEG, 6, GRAY),
    DULUTH_SAULT_ST_MARIE(DULUTH, SAULT_ST_MARIE, 3, GRAY),
    SAULT_ST_MARIE_TORONTO(SAULT_ST_MARIE, TORONTO, 2, GRAY),
    MONTREAL_TORONTO(MONTREAL, TORONTO, 3, GRAY),
    BOSTON_MONTREAL_1(BOSTON, MONTREAL, 2, GRAY, 1),
    BOSTON_MONTREAL_2(BOSTON, MONTREAL, 2, GRAY, -1),
    PITTSBURGH_TORONTO(PITTSBURGH, TORONTO, 2, GRAY),

    // 8 EAST OF ATLANTA
    PITTSBURGH_WASHINGTON(PITTSBURGH, WASHINGTON, 2, GRAY),
    PITTSBURGH_RALEIGH(PITTSBURGH, RALEIGH, 2, GRAY),
    RALEIGH_WASHINGTON_1(RALEIGH, WASHINGTON, 2, GRAY, 1),
    RALEIGH_WASHINGTON_2(RALEIGH, WASHINGTON, 2, GRAY, -1),
    CHARLESTON_RALEIGH(CHARLESTON, RALEIGH, 2, GRAY),
    ATLANTA_CHARLESTON(ATLANTA, CHARLESTON, 2, GRAY),
    ATLANTA_RALEIGH_1(ATLANTA, RALEIGH, 2, GRAY, 1),
    ATLANTA_RALEIGH_2(ATLANTA, RALEIGH, 2, GRAY, -1),

    // 6 WEST OF ATLANTA
    ATLANTA_NASHVILLE(ATLANTA, NASHVILLE, 1, GRAY),
    NASHVILLE_SAINT_LOUIS(NASHVILLE, SAINT_LOUIS, 2, GRAY),
    LITTLE_ROCK_SAINT_LOUIS(LITTLE_ROCK, SAINT_LOUIS, 2, GRAY),
    LITTLE_ROCK_OKLAHOMA_CITY(LITTLE_ROCK, OKLAHOMA_CITY, 2, GRAY),
    DALLAS_LITTLE_ROCK(DALLAS, LITTLE_ROCK, 2, GRAY),
    HOUSTON_NEW_ORLEANS(HOUSTON, NEW_ORLEANS, 2, GRAY);

    private MapCity city1;
    private MapCity city2;
    private int length;
    private MapRouteColor color;
    private int dir;

    MapRoute(MapCity city1, MapCity city2, int length, MapRouteColor color) {
        this.city1 = city1;
        this.city2 = city2;
        this.length = length;
        this.color = color;
    }

    MapRoute(MapCity city1, MapCity city2, int length, MapRouteColor color, int dir) {
        this.city1 = city1;
        this.city2 = city2;
        this.length = length;
        this.color = color;
        this.dir = dir;
    }

    public MapCity getCity1() {
        return city1;
    }

    public MapCity getCity2() {
        return city2;
    }

    public int getLength() {
        return length;
    }

    public int getColor() {
        return color.getColor();
    }

    public int getDir() {
        return dir;
    }
}
